flowchart/urls.py
from django.urls import path, include
from . import views

app_name = "flowchart"


urlpatterns = [
    path('api/v1/', include('flowchart.api.v1.urls')),
    path('view/<str:pk>/', views.flowchart_view, name='flowchart_view'),
    path('history-dashboard/', views.history_list, name='history-list'),
    path('history/<str:pk>/', views.history_detail, name='history-detail'),

]

index/urls.py
from django.urls import path
from . import views


app_name = 'index'
urlpatterns = [
    path('', views.index_view, name='dashboard'),
]

js_test/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

import notifications.urls

admin.site.site_header = 'DigiKala BCM Admin'

schema_view = get_schema_view(
    openapi.Info(
        title="BCM API",
        default_version='v1',
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=[permissions.IsAuthenticated],
)

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('flowchart/', include('flowchart.urls')),
                  path('diagram/', include('diagram.urls')),
                  url('^inbox/notifications/', include(notifications.urls, namespace='notifications')),
                  path('', include('index.urls')),
                  path('api-auth/', include('rest_framework.urls')),
                  path('users/', include('users.urls')),
                  path('swagger/api.json', schema_view.without_ui(cache_timeout=0), name='schema-json'),
                  path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
                  path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
              ] + \
              static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + \
              static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notifications/urls.py
''' Django notification urls file '''
# -*- coding: utf-8 -*-
from distutils.version import StrictVersion  # pylint: disable=no-name-in-module,import-error

from django import get_version

from . import views

if StrictVersion(get_version()) >= StrictVersion('2.0'):
    from django.urls import re_path as pattern
else:
    from django.conf.urls import url as pattern


urlpatterns = [
    pattern(r'^$', views.AllNotificationsList.as_view(), name='all'),
    pattern(r'^unread/$', views.UnreadNotificationsList.as_view(), name='unread'),
    pattern(r'^mark-all-as-read/$', views.mark_all_as_read, name='mark_all_as_read'),
    pattern(r'^mark-as-read/(?P<slug>\d+)/$', views.mark_as_read, name='mark_as_read'),
    pattern(r'^mark-as-unread/(?P<slug>\d+)/$', views.mark_as_unread, name='mark_as_unread'),
    pattern(r'^delete/(?P<slug>\d+)/$', views.delete, name='delete'),
    pattern(r'^api/unread_count/$', views.live_unread_notification_count, name='live_unread_notification_count'),
    pattern(r'^api/all_count/$', views.live_all_notification_count, name='live_all_notification_count'),
    pattern(r'^api/unread_list/$', views.live_unread_notification_list, name='live_unread_notification_list'),
    pattern(r'^api/all_list/', views.live_all_notification_list, name='live_all_notification_list'),
]

app_name = 'notifications'

flowchart/api/v1/views.py
import io

import requests
import urllib3
from django.db.models import Count, Sum
from django.db.models.functions import TruncMonth
from rest_framework.decorators import api_view, authentication_classes, permission_classes
from rest_framework.permissions import IsAuthenticated, AllowAny
from rest_framework.viewsets import ModelViewSet

from flowchart.models import Flowchart, Location, HistoryChange, ContingencyPlan, Screenshot
from rest_framework import viewsets, status
from rest_framework.response import Response
from .serializers import FlowchartSerializer, LocationSerializer, HistoryChangeSerializer, ContingencyPlanSerializer, \
    ScreenshotSerializer
from rest_framework.authentication import SessionAuthentication, BasicAuthentication
from django_filters.rest_framework import DjangoFilterBackend
from flowchart.utils import f_reset, f_end, f_create, minio_setter, minio_getter, get_connection
from PIL import Image


class FlowchartViewSet(viewsets.ModelViewSet):
    """
    A simple ViewSet for listing or retrieving users.
    """
    permission_classes = [IsAuthenticated]
    serializer_class = FlowchartSerializer
    queryset = Flowchart.objects.all().order_by('-is_active')
    filter_backends = [DjangoFilterBackend]
    filterset_fields = ['primary', 'is_active']


class LocationViewSet(viewsets.ModelViewSet):
    """
    A simple ViewSet for listing or retrieving users.
    """
    permission_classes = [IsAuthenticated]
    serializer_class = LocationSerializer
    queryset = Location.objects.all()


class ContingencyPlanViewSet(viewsets.ModelViewSet):
    serializer_class = ContingencyPlanSerializer
    queryset = ContingencyPlan.objects.all()


@api_view(['Get'])
@authentication_classes([SessionAuthentication, BasicAuthentication])
@permission_classes([IsAuthenticated])
def incident_per_location(request):
    active_incidents = Location.objects.values('name').annotate(total=Count('flowchart')).order_by('name')

    closed_incident = Location.objects.values('name', 'incident_number').order_by('name')

    data = {}
    for obj1, obj2 in zip(closed_incident, active_incidents):
        data[obj1['name']] = {'closed': obj1['incident_number'], 'active': obj2['total']}

    return Response(data)


class HistoryChangeViewSet(viewsets.ModelViewSet):
    serializer_class = HistoryChangeSerializer
    queryset = HistoryChange.objects.all()


@api_view(['Post'])
def flowchart_utility(request):
    """ Below view get 3 types of tasks to perform.
        1. Create an instance from a flowchart template.
        2. reset it.
        3. ending it.
        tip: The only difference between reset and end in front is creating a log history from finished flowchart.
    """
    flowchart_id = request.data.get('flowchart_id')
    location_id = request.data.get('location_id')
    task = request.data.get('task')

    if not flowchart_id:
        return Response({"message": "No flowchart Id provided"}, status=status.HTTP_400_BAD_REQUEST)

    try:
        flowchart = Flowchart.objects.get(id=flowchart_id)
    except Flowchart.DoesNotExist:
        return Response({"message": "Invalid flowchart id"}, status=status.HTTP_400_BAD_REQUEST)

    if task == 'create':
        return f_create(flowchart_id, location_id)
    elif task == 'reset':
        return f_reset(flowchart_id)
    elif task == 'end':
        return f_end(flowchart_id, request)


@api_view(['Get'])
def incident_per_location(request):
    temp = {}
    opened = []
    queryset = Flowchart.objects.all()
    locs = queryset.exclude(location=None).values('location__name').annotate(count=Sum('incident_counter')).order_by('location__name')
    temp['names'] = locs.values_list('location__name', flat=True)
    temp['closed'] = locs.values_list('count', flat=True)
    for loc_name in temp['names']:
        opens = queryset.filter(is_active=True, location__name=loc_name).values('location__name').annotate(count=Count('is_active'))
        if len(opens) == 0:
            opened.append(0)
        else:
            opened.append(opens[0]['count'])

    temp['opened'] = opened
    return Response(temp, status=status.HTTP_200_OK)


@api_view(['Get'])
def total_incident(request):
    temp = {}
    queryset = Flowchart.objects.all()
    closed = queryset.values('incident_counter').aggregate(count=Sum('incident_counter'))['count']
    opened = queryset.filter(is_active=True).count()
    temp['closed'] = closed
    temp['open'] = opened
    return Response(temp, status=status.HTTP_200_OK)


@api_view(['Get'])
def incident_per_contingency(request):
    temp = {}
    counts = []
    names = []
    flowchart_names = list(Flowchart.objects.filter(primary=True).values_list('name', flat=True).order_by('name'))
    for name in flowchart_names:
        c = Flowchart.objects.filter(primary=False, name__contains=name).values('incident_counter').aggregate(count=Sum('incident_counter'))['count']
        counts.append(c)
        names.append(name)
    temp['names'] = names
    temp['counts'] = counts
    return Response(temp, status=status.HTTP_200_OK)


@api_view(['Get'])
def incident_per_month(request):
    temp = {}
    months = []
    counts = []
    histories = HistoryChange.objects.annotate(month=TruncMonth('j_initial_date')).values('month').annotate(count=Count('id')).values('month', 'count')
    for item in histories:
        months.append('-'.join(str(item['month']).split('-')[0:2]))
        counts.append(item['count'])
    temp['months'] = months
    temp['counts'] = counts
    return Response(temp, status=status.HTTP_200_OK)


class ScreenViewSet(ModelViewSet):

    permission_classes = [IsAuthenticated]
    serializer_class = ScreenshotSerializer
    queryset = Screenshot.objects.all()

    def create(self, request, *args, **kwargs):
        data = request.data
        if not data.get('flowchart'):
            image = data.get('image')
            image_name = image.name
            flowchart_id = image_name.split('.png')[0]

            try:
                flowchart = Flowchart.objects.get(id=flowchart_id)
                data['name'] = flowchart.id
                data['flowchart'] = flowchart.id
            except Flowchart.DoesNotExist:
                return Response({"detail": "Flowchart Does not exists"}, status=status.HTTP_404_NOT_FOUND)

        serializer = self.get_serializer(data=data)
        if serializer.is_valid(raise_exception=True):
            serializer.save()

        return Response({"detail": serializer.data}, status=status.HTTP_201_CREATED)

    def retrieve(self, request, *args, **kwargs):
        instance = self.get_object()
        serializer = self.get_serializer(instance)
        return Response(serializer.data)

flowchart/views.py
import json
from django.http import JsonResponse
from diagram.models import Block
from users.models import Member
from .models import Flowchart, HistoryChange
from django.shortcuts import render, get_object_or_404
from django.db.models import Q
from django.contrib.auth.decorators import login_required
import jdatetime


@login_required(login_url='users:login')
def flowchart_view(request, pk):
    context = {}

    try:
        flowchart = Flowchart.objects.get(pk=pk)
        t = flowchart.triggered_date
        if t:
            j = jdatetime.datetime.fromgregorian(day=t.day, month=t.month, year=t.year, hour=t.hour, minute=t.minute)
            context['triggered_date'] = j
        context['flowchart_id'] = flowchart.id
        context['flowchart_name'] = flowchart.__str__().title()
        blocks = Block.objects.filter(Q(is_approved=True) | Q(is_active=True)).order_by('-updated_date')
        blocks = blocks.filter(flowchart_id=flowchart.id)
        context['blocks'] = blocks
        context['members'] = Member.objects.all()
    except Flowchart.DoesNotExist:
        return JsonResponse({'error': f'flowchart does not exists'})

    if flowchart.primary:
        return render(request, 'flowchart/primary_flowchart.html', context)

    return render(request, 'flowchart/flowchart.html', context)


@login_required(login_url='users:login')
def history_detail(request, pk):
    context = {}
    history = get_object_or_404(HistoryChange, pk=pk)
    block_h = history.block_history
    comment_h = history.comment_history
    flowchart = get_object_or_404(Flowchart, pk=history.flowchart.id)
    email_responses = history.email_response

    context['block_history'] = block_h
    context['comment_history'] = comment_h
    context['flowchart'] = flowchart
    context['history_id'] = history.id
    context['email_responses'] = email_responses

    return render(request, 'flowchart/history_detail.html', context)


@login_required(login_url='users:login')
def history_list(request):
    context = {}
    histories = HistoryChange.objects.filter(flowchart__primary=False).order_by('-initial_date')
    for history in histories:
        m = history.initial_date
        jalali = jdatetime.datetime.fromgregorian(day=m.day, month=m.month, year=m.year, hour=m.hour, minute=m.minute)
        history.jalali = jalali
    context['histories'] = histories

    return render(request, 'flowchart/history_list.html', context)

flowchart/templates/flowchart/history_detail.html
{% extends 'base/base.html' %}
{% load static %}
{% load replace %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}
    {% endblock %}
</head>
<body>

{% block dashboard %}
    <h4>{{ flowchart }} History Detail</h4>
{% endblock %}

{% block content %}
    <div style="text-align: center">
        <h2>Blocks History</h2>
        <hr style="background-color: black">
        <div class="card-body table-responsive">
            <table id="dtverTable" class="table table-striped table-bordered table-sm">
                <thead class="thead-dark">
                <tr>
                    <th style="min-width:200px" class="text-center" scope="col">Block</th>
                    <th class="text-center" scope="col">By User</th>
                    <th class="text-center" scope="col">Date</th>
                    <th class="text-center" scope="col">State</th>
                    <th class="text-center" scope="col">Action</th>
                </tr>
                </thead>
                <tbody>

                {% for k, v in block_history.items %}
                    <tr class="text-center">
                        <td class="text-center"> {{ v.label }}</td>
                        <td class="text-center"> {{ v.user }}</td>
                        <td class="text-center"> {{ v.change_date }}</td>
                        <td class="text-center"> {{ v.changes.0.field|replace_active }}</td>
                        <td class="text-center">
                            <button class="btn btn-outline-info" type="submit" onclick="getCommentHistory({{ k }})">Show
                                Comments
                            </button>
                        </td>
                    </tr>

                {% endfor %}

                </tbody>
            </table>
        </div>
    </div>
    {% if email_responses.items|length > 0 %}
    <div style="text-align: center">
        <h2>Email Responses History</h2>
        <hr style="background-color: black">
        <div class="card-body table-responsive">
            <table id="dtverTable" class="table table-striped table-bordered table-sm">
                <thead class="thead-dark">
                <tr>
                    <th class="text-center" scope="col">By User</th>
                    <th class="text-center" scope="col">Date</th>
                    <th class="text-center" scope="col">Message</th>
                </tr>
                </thead>
                <tbody>
                {% for k, v in email_responses.items %}
                    <tr class="text-center">
                        <td class="text-center"> {{ v.member }}</td>
                        <td class="text-center"> {{ v.date|to_jalali }}</td>
                        <td class="text-center"> {{ v.message }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    {% endif %}

    <div style="text-align: center">
        <hr style="background-color: black">
        <h2>Comments History</h2>
        <div class="card-body table-responsive" id="comment-card">

        </div>
    </div>

    <script>

        $(document).ready(function () {
            $('#dtverTable').DataTable({
                "scrollY": "600px",
                "scrollCollapse": true,
            });
            $('.dataTables_length').addClass('bs-select');
        });

        function getCommentHistory(block_id) {
            var tableCard = document.getElementById("comment-card")
            tableCard.innerHTML = ""
            $.ajax({
                type: 'GET',
                dataType: "json",
                url: "/flowchart/api/v1/HistoryChange/" + {{ history_id }} +"/",
                success: function (data, status, xhr) {

                    var commentHistory = JSON.parse(data.comment_history)

                    var table = document.createElement("table")
                    table.classList = "table table-striped table-bordered table-sm"
                    table.id = "comment"
                    var head = document.createElement("thead")
                    head.classList = "thead-light"

                    var body = document.createElement("tbody")

                    var th1 = document.createElement("th")
                    th1.classList = "text-center"
                    th1.scope = "col"
                    th1.innerText = "block"

                    var th2 = document.createElement("th")
                    th2.classList = "text-center"
                    th2.scope = "col"
                    th2.innerText = "By User"

                    var th3 = document.createElement("th")
                    th3.classList = "text-center"
                    th3.scope = "col"
                    th3.innerText = "Date"

                    var th4 = document.createElement("th")
                    th4.classList = "text-center"
                    th4.scope = "col"
                    th4.innerText = "Text"

                    var tr = document.createElement("tr")

                    tr.appendChild(th1)
                    tr.appendChild(th2)
                    tr.appendChild(th3)
                    tr.appendChild(th4)

                    head.appendChild(tr)


                    for (let i = 0; i < Object.keys(commentHistory).length; i++) {
                        var id = Object.keys(commentHistory)[i]
                        var info = commentHistory[id]
                        if (info.block_id === block_id) {
                            var tr = document.createElement('tr')
                            tr.classList = "text-center"

                            var td1 = document.createElement("td")
                            td1.classList = "text-center"
                            td1.innerHTML = info.block

                            var td2 = document.createElement("td")
                            td2.classList = "text-center"
                            td2.innerHTML = info.author

                            var td3 = document.createElement("td")
                            td3.classList = "text-center"
                            td3.innerHTML = info.date

                            var td4 = document.createElement("td")
                            td4.classList = "text-center"
                            td4.innerHTML = info.text

                            tr.appendChild(td1)
                            tr.appendChild(td2)
                            tr.appendChild(td3)
                            tr.appendChild(td4)

                            body.appendChild(tr)

                        }

                    }
                    table.appendChild(head)
                    table.appendChild(body)

                    tableCard.appendChild(table)
                    $(document).ready(function () {
                        $('#comment').DataTable({
                            "scrollY": "600px",
                            "scrollCollapse": true,
                        });
                        $('.dataTables_length').addClass('bs-select');
                    });
                }
            });
            element = document.getElementById("comment-card");
            element.scrollIntoView();
        }

    </script>

{% endblock %}
</body>
</html>

flowchart/templates/flowchart/history_list.html
{% extends 'base/base.html' %}
{% load replace %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}
        History Dashboard
    {% endblock %}
</head>
<body>

{% block dashboard %}
    History Dashboard
{% endblock %}

{% block content %}
    <div class="card-body table-responsive">

        <table id="dtverTable" class="table table-striped table-bordered table-sm">
            <thead class="thead-dark">
            <tr>
                <th style="min-width:200px" class="text-center" scope="col">Location</th>
                <th class="text-center" scope="col">Contingency Plan</th>
                <th class="text-center" scope="col">Start Date</th>
                <th class="text-center" scope="col">View History</th>

            </tr>
            </thead>
            <tbody>

            {% for history in histories %}
                <tr class="text-center">

                    <td class="text-center"> {{ history.flowchart.location.name}}</td>
                    <td class="text-center"> {{ history.flowchart.name|upper_case|capfirst }}</td>
                    <td class="text-center"> {{ history.jalali }}</td>

                    <td class="text-center">
                        <a href="{% url 'flowchart:history-detail' pk=history.id %}" class="btn btn-sm btn-outline-dark">View History </a>
                    </td>

                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

    <script>
        $(document).ready(function () {
            $('#dtverTable').DataTable({
                "scrollY": "600px",
                "scrollCollapse": true,
            });
            $('.dataTables_length').addClass('bs-select');
        });


    </script>

{% endblock %}

</body>
</html>