index/urls.py
from django.urls import path
from . import views


app_name = 'index'
urlpatterns = [
    path('', views.index_view, name='dashboard'),
]

js_test/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

import notifications.urls

admin.site.site_header = 'DigiKala BCM Admin'

schema_view = get_schema_view(
    openapi.Info(
        title="BCM API",
        default_version='v1',
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=[permissions.IsAuthenticated],
)

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('flowchart/', include('flowchart.urls')),
                  path('diagram/', include('diagram.urls')),
                  url('^inbox/notifications/', include(notifications.urls, namespace='notifications')),
                  path('', include('index.urls')),
                  path('api-auth/', include('rest_framework.urls')),
                  path('users/', include('users.urls')),
                  path('swagger/api.json', schema_view.without_ui(cache_timeout=0), name='schema-json'),
                  path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
                  path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
              ] + \
              static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + \
              static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notifications/urls.py
''' Django notification urls file '''
# -*- coding: utf-8 -*-
from distutils.version import StrictVersion  # pylint: disable=no-name-in-module,import-error

from django import get_version

from . import views

if StrictVersion(get_version()) >= StrictVersion('2.0'):
    from django.urls import re_path as pattern
else:
    from django.conf.urls import url as pattern


urlpatterns = [
    pattern(r'^$', views.AllNotificationsList.as_view(), name='all'),
    pattern(r'^unread/$', views.UnreadNotificationsList.as_view(), name='unread'),
    pattern(r'^mark-all-as-read/$', views.mark_all_as_read, name='mark_all_as_read'),
    pattern(r'^mark-as-read/(?P<slug>\d+)/$', views.mark_as_read, name='mark_as_read'),
    pattern(r'^mark-as-unread/(?P<slug>\d+)/$', views.mark_as_unread, name='mark_as_unread'),
    pattern(r'^delete/(?P<slug>\d+)/$', views.delete, name='delete'),
    pattern(r'^api/unread_count/$', views.live_unread_notification_count, name='live_unread_notification_count'),
    pattern(r'^api/all_count/$', views.live_all_notification_count, name='live_all_notification_count'),
    pattern(r'^api/unread_list/$', views.live_unread_notification_list, name='live_unread_notification_list'),
    pattern(r'^api/all_list/', views.live_all_notification_list, name='live_all_notification_list'),
]

app_name = 'notifications'

users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('contacts/', views.ContactListView.as_view(), name='contacts'),
    path('edit-contact/<str:pk>/', views.edit_member, name='edit-contact'),
    path('delete-contact/<str:pk>/', views.delete_member, name='delete-contact'),
    path('mail_response_view/<str:random_text>/', views.mail_response_view, name='mail_response_view'),
    path('sms-panel/', views.sms_panel_view, name='sms-panel'),
    path('save_member_session/<str:member_id>/', views.save_member_session, name='save_member_session'),
    path('update_user/', views.update_user, name='update_user'),
    path('email-response/', views.email_response_view, name='email_response'),
    path('mark_as_read/', views.mark_as_read, name='mark_as_read'),
    path('api/v1/', include('users.api.v1.urls')),
    path('', include('django.contrib.auth.urls')),

]

notifications/models.py
from swapper import swappable_setting

from .base.models import AbstractNotification, notify_handler  # noqa


class Notification(AbstractNotification):

    class Meta(AbstractNotification.Meta):
        abstract = False
        swappable = swappable_setting('notifications', 'Notification')

notifications/views.py
# -*- coding: utf-8 -*-
''' Django Notifications example views '''
from distutils.version import \
    StrictVersion  # pylint: disable=no-name-in-module,import-error

from django import get_version
from django.contrib.auth.decorators import login_required
from django.forms import model_to_dict
from django.shortcuts import get_object_or_404, redirect
from django.utils.decorators import method_decorator
from django.views.decorators.cache import never_cache
from django.views.generic import ListView
from notifications import settings
from notifications.settings import get_config
from notifications.utils import id2slug, slug2id
from swapper import load_model
from django.contrib.humanize.templatetags.humanize import naturaltime

Notification = load_model('notifications', 'Notification')

if StrictVersion(get_version()) >= StrictVersion('1.7.0'):
    from django.http import JsonResponse  # noqa
else:
    # Django 1.6 doesn't have a proper JsonResponse
    import json
    from django.http import HttpResponse  # noqa

    def date_handler(obj):
        return obj.isoformat() if hasattr(obj, 'isoformat') else obj

    def JsonResponse(data):  # noqa
        return HttpResponse(
            json.dumps(data, default=date_handler),
            content_type="application/json")


class NotificationViewList(ListView):
    template_name = 'notifications/list.html'
    context_object_name = 'notifications'
    paginate_by = settings.get_config()['PAGINATE_BY']

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(NotificationViewList, self).dispatch(
            request, *args, **kwargs)


class AllNotificationsList(NotificationViewList):
    """
    Index page for authenticated user
    """

    def get_queryset(self):
        if settings.get_config()['SOFT_DELETE']:
            qset = self.request.user.notifications.active()
        else:
            qset = self.request.user.notifications.all()
        return qset


class UnreadNotificationsList(NotificationViewList):

    def get_queryset(self):
        return self.request.user.notifications.unread()


@login_required
def mark_all_as_read(request):
    request.user.notifications.mark_all_as_read()

    _next = request.GET.get('next')

    if _next:
        return redirect(_next)
    return redirect('notifications:unread')


@login_required
def mark_as_read(request, slug=None):
    notification_id = slug2id(slug)

    notification = get_object_or_404(
        Notification, recipient=request.user, id=notification_id)
    notification.mark_as_read()

    _next = request.GET.get('next')

    if _next:
        return redirect(_next)

    return redirect('notifications:unread')


@login_required
def mark_as_unread(request, slug=None):
    notification_id = slug2id(slug)

    notification = get_object_or_404(
        Notification, recipient=request.user, id=notification_id)
    notification.mark_as_unread()

    _next = request.GET.get('next')

    if _next:
        return redirect(_next)

    return redirect('notifications:unread')


@login_required
def delete(request, slug=None):
    notification_id = slug2id(slug)

    notification = get_object_or_404(
        Notification, recipient=request.user, id=notification_id)

    if settings.get_config()['SOFT_DELETE']:
        notification.deleted = True
        notification.save()
    else:
        notification.delete()

    _next = request.GET.get('next')

    if _next:
        return redirect(_next)

    return redirect('notifications:all')


@never_cache
def live_unread_notification_count(request):
    try:
        user_is_authenticated = request.user.is_authenticated()
    except TypeError:  # Django >= 1.11
        user_is_authenticated = request.user.is_authenticated

    if not user_is_authenticated:
        data = {
            'unread_count': 0
        }
    else:
        data = {
            'unread_count': request.user.notifications.unread().count(),
        }
    return JsonResponse(data)


@never_cache
def live_unread_notification_list(request):
    ''' Return a json with a unread notification list '''
    try:
        user_is_authenticated = request.user.is_authenticated()
    except TypeError:  # Django >= 1.11
        user_is_authenticated = request.user.is_authenticated

    if not user_is_authenticated:
        data = {
            'unread_count': 0,
            'unread_list': []
        }
        return JsonResponse(data)

    default_num_to_fetch = get_config()['NUM_TO_FETCH']
    try:
        # If they don't specify, make it 5.
        num_to_fetch = request.GET.get('max', default_num_to_fetch)
        num_to_fetch = int(num_to_fetch)
        if not (1 <= num_to_fetch <= 100):
            num_to_fetch = default_num_to_fetch
    except ValueError:  # If casting to an int fails.
        num_to_fetch = default_num_to_fetch

    unread_list = []

    for notification in request.user.notifications.unread()[0:num_to_fetch]:
        struct = model_to_dict(notification)
        struct['slug'] = id2slug(notification.id)
        if notification.actor:
            struct['actor'] = str(notification.actor).title()
        if notification.target:
            struct['target'] = str(notification.target)
        if notification.action_object:
            struct['action_object'] = str(notification.action_object)
        if notification.data:
            struct['data'] = notification.data
        struct['natural_time'] = naturaltime(notification.timestamp)
        unread_list.append(struct)
        if request.GET.get('mark_as_read'):
            notification.mark_as_read()
    data = {
        'unread_count': request.user.notifications.unread().count(),
        'unread_list': unread_list
    }
    return JsonResponse(data)


@never_cache
def live_all_notification_list(request):
    ''' Return a json with a unread notification list '''
    try:
        user_is_authenticated = request.user.is_authenticated()
    except TypeError:  # Django >= 1.11
        user_is_authenticated = request.user.is_authenticated

    if not user_is_authenticated:
        data = {
            'all_count': 0,
            'all_list': []
        }
        return JsonResponse(data)

    default_num_to_fetch = get_config()['NUM_TO_FETCH']
    try:
        # If they don't specify, make it 5.
        num_to_fetch = request.GET.get('max', default_num_to_fetch)
        num_to_fetch = int(num_to_fetch)
        if not (1 <= num_to_fetch <= 100):
            num_to_fetch = default_num_to_fetch
    except ValueError:  # If casting to an int fails.
        num_to_fetch = default_num_to_fetch

    all_list = []

    for notification in request.user.notifications.all()[0:num_to_fetch]:
        struct = model_to_dict(notification)
        struct['slug'] = id2slug(notification.id)
        if notification.actor:
            struct['actor'] = str(notification.actor)
        if notification.target:
            struct['target'] = str(notification.target)
        if notification.action_object:
            struct['action_object'] = str(notification.action_object)
        if notification.data:
            struct['data'] = notification.data
        all_list.append(struct)
        if request.GET.get('mark_as_read'):
            notification.mark_as_read()
    data = {
        'all_count': request.user.notifications.count(),
        'all_list': all_list
    }
    return JsonResponse(data)


def live_all_notification_count(request):
    try:
        user_is_authenticated = request.user.is_authenticated()
    except TypeError:  # Django >= 1.11
        user_is_authenticated = request.user.is_authenticated

    if not user_is_authenticated:
        data = {
            'all_count': 0
        }
    else:
        data = {
            'all_count': request.user.notifications.count(),
        }
    return JsonResponse(data)

users/views.py
from django.shortcuts import redirect
from django.contrib.auth import authenticate, login
from .forms import LoginForm, MemberForm, CustomUserForm
from django.views.generic.list import ListView
from django.shortcuts import render
from users.models import CustomUser, Member
from diagram.models import Block
from diagram.models import Comment
from django.contrib import messages
from django.contrib.auth.decorators import login_required
import jdatetime
from django.shortcuts import get_object_or_404
from notifications.models import Notification


def login_view(request):
    if request.user.is_authenticated:
        return redirect('index:dashboard')
    form = LoginForm(request.POST or None)

    if request.method == "POST":
        if form.is_valid():
            email = form.cleaned_data.get("email")
            password = form.cleaned_data.get("password")
            user = authenticate(username=email, password=password)
            if user:
                login(request, user)
                return redirect('index:dashboard')
            else:
                form.add_error('email', 'Email or Password is not correct')

    return render(request, "users/login.html", {"form": form})


class ContactListView(ListView):

    model = Member
    paginate_by = 9  # if pagination is desired
    template_name = 'users/contacts.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = MemberForm()
        return context

    def post(self, request):
        form = MemberForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect(request.META['HTTP_REFERER'])
        else:
            messages.error(request,  'The Email field or Phone number field is not correct' )
            return render(request, 'users/contacts.html', {'form': form})


@login_required(login_url='users:login')
def mail_response_view(request, random_text):

    context = {'state': False}
    try:
        random_text = random_text.split('_')
        user_url, block_id = random_text[0:2]
        user = CustomUser.objects.get(rand_text=user_url)
        block = Block.objects.get(id=block_id, is_active=True)
    except:
        return render(request, 'users/email_response.html', context)

    for group in block.user_groups.all():
        for sub_users in group.user_set.all():
            if user == sub_users:
                context['state'] = True
                break
        if context['state']:
            break

    if not context['state']:
        return render(request, 'users/email_response.html', context)

    try:
        comment = Comment.objects.get(author=user, block=block, text='Email received')
    except Comment.DoesNotExist:
        comment = Comment(author=user, block=block, text='Email received', label='Email Notif')
        comment.save()
    context['state'] = True
    return render(request, 'users/email_response.html', context)


@login_required(login_url='users:login')
def sms_panel_view(request):
    context = {}
    saved_member_id = request.session.get("member_id")
    if saved_member_id:
        context['saved_member'] = Member.objects.filter(id=saved_member_id)
        context['saved_member_id'] = int(saved_member_id)
    members = Member.objects.all()
    context['members'] = members

    return render(request, 'users/send_message.html', context)


@login_required(login_url='users:login')
def save_member_session(request, member_id):
    request.session["member_id"] = member_id
    return redirect('users:sms-panel')


@login_required(login_url='users:login')
def update_user(request):
    l = request.user.last_login
    last_login = str(jdatetime.datetime.fromgregorian(day=l.day, month=l.month, year=l.year,
                                                      hour=l.hour, minute=l.minute))
    user_form = CustomUserForm(instance=request.user)

    if request.method == 'POST':
        user_form = CustomUserForm(request.POST, request.FILES, instance=request.user)

        if user_form.is_valid():
            user_form.save()
            return redirect('index:dashboard')

    return render(request, 'users/update_user.html', {'user_form': user_form, 'last_login': last_login})


def email_response_view(request):
    notif = Notification.objects.filter(unread=True, recipient=request.user)

    if request.method == 'POST':
        notif.mark_all_as_read()
        return render(request, 'users/notifications.html')

    return render(request, 'users/notifications.html', {'notif_unread': notif})


def mark_as_read(request):
    notif = Notification.objects.filter(unread=True,recipient=request.user)
    notif.mark_all_as_read()
    return redirect(request.META['HTTP_REFERER'])


def edit_member(request, pk):
    instance = get_object_or_404(Member, id=pk)
    if request.method == 'GET':
        context = {'form': MemberForm(instance=instance)}
        return render(request, 'users/update_member.html', context)

    elif request.method == 'POST':
        form = MemberForm(request.POST, instance=instance)
        if form.is_valid():
            form.save()
            return redirect('users:contacts')
        else:
            return render(request, 'users/update_member.html', {'form': form})


def delete_member(request, pk):
    instance = get_object_or_404(Member, id=pk)
    instance.delete()
    return redirect('users:contacts')

users/templates/users/contacts.html
{% extends 'base/base.html' %}
{% load static %}

{% block dashboard %}

{% endblock %}

{% block  content %}


    <div class="col">
        <div class="card card-dark">
            <div class="card-header ">
                <h1 class="card-title primary">Create Contact</h1>
                <p class="card-category"></p>
            </div>

            <div class="card-body">
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <h6 style="color: red">{{ form.errors }}</h6>
                    <div style="alignment: center" class="form-group row">
                        <div class="col-6">
                            {{ form.first_name.label }}
                            {{ form.first_name }}
                            <br>
                            {{ form.last_name.label }}
                            {{ form.last_name }}
                            <br>
                            <div class="custom-file">
                                <label class="custom-file-label" for="exampleInputFile">Choose file</label>
                                {{ form.profile_image }}
                            </div>

                        </div>
                        <div class="col-6">
                            {{ form.email.label }}
                            {{ form.email }}
                            <br>
                            {{ form.mobile_number.label }}
                            {{ form.mobile_number }}
                            <br>
                            <div class="form-check">
                                {{ form.department }}

                                <label class="form-check-label">Checkbox</label>
                            </div>
                        </div>

                    </div>

                    <div class="row col-12">
                        <button type="submit" class="btn btn-primary">Add Contact</button>
                    </div>
                </form>
            </div>

        </div>
    </div>
    <!-- Default box -->
    <div class="card card-solid">
        <div class="card-body pb-0">
            <div class="row">
                {% for member in object_list %}
                    <div class="col-12 col-sm-6 col-md-4 d-flex align-items-stretch flex-column">
                        <div class="card bg-light d-flex flex-fill">
                            <div class="card-header text-muted border-bottom-0">
                                {{ member.department }}
                            </div>
                            <div class="card-body pt-0">
                                <div class="row">
                                    <div class="col-7">
                                        <h2 class="lead"><b>{{ member.full_name }}</b></h2>
                                        <p class="text-muted text-sm"><b>Email: </b> {{ member.email }}</p>
                                        <p class="text-muted text-sm"><b>Phone Number: </b> {{ member.mobile_number }}
                                        </p>
                                    </div>
                                    <div class="col-5 text-center">
                                        <img src="{{ member.profile_image.url }}" alt="user-avatar"
                                             class="img-circle img-fluid"
                                             style="border-radius: 50%!important; width: 150px; height: 150px; object-fit: fill">
                                    </div>
                                </div>
                            </div>
                            <div class="card-footer">
                                <div class="text-right">
                                    <a href="{% url 'users:save_member_session' member.id %}"
                                       class="btn btn-sm bg-green">
                                        <i class="fas fa-comments"> Send Message</i>
                                    </a>
                                    <a href="{% url 'users:edit-contact' member.id %}"
                                       class="btn btn-sm bg-black">
                                        <i class="fas fa-comments"> Edit Contact</i>
                                    </a>
                                    <a href="{% url 'users:delete-contact' member.id %}"
                                       class="btn btn-sm bg-red">
                                        <i class="fas fa-comments"> Delete Contact</i>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
        <!-- /.card-body -->
        <div class="card-footer">
            <nav aria-label="Contacts Page Navigation">
                <ul class="pagination justify-content-center m-0">
                    {% for i in paginator.page_range %}
                        {% if page_obj.number == i %}
                            <li class="page-item active"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>

                        {% else %}
                            <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                        {% endif %}
                    {% endfor %}

                </ul>
            </nav>
        </div>
        <!-- /.card-footer -->
    </div>
    <!-- /.card -->



{% endblock %}

users/templates/users/email.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>BCM - Email</title>
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css2?family=Noto+Sans+Arabic&display=swap" >

</head>
<body style="font-weight: bold;direction: rtl">
<section class="main" style="background-color: rgba(214,221,236,0.48) !important; padding: 15px;box-sizing: border-box">
    <p class="image" style="text-align: center">
        <img src="https://oklozo.stripocdn.email/content/guids/3e3dbdd3-0d1a-4d99-a03b-fc2ba51665dc/images/79831610455841928.png" alt="" width="300" style="width:300px;">
    </p>
    <section class="title">
        <p style="text-align: center;font-size: 20px;background-color: crimson;color: white;margin-top: 15px;direction: ltr">Crisis Alert !</p>
        <hr style="background-color: #151515">
        <p style="font-family: 'Noto Sans Arabic', sans-serif;margin-top: 15px"> جناب آقای / خانم {{ name }}<br>
            با توجه به وقوع بحران <span style="color: red;font-weight: bold"> {{ flowchart_name }}</span> لیست اقدامات شما به شرح زیر است :</p>
    </section>
    {% if current_action %}
    <p style="font-family: 'Noto Sans Arabic', sans-serif;text-align: justify"> <span style="color: red">اقدامات فعلی :</span> <br>
        {{ current_action }}
    </p>
    {% endif %}
    {% if next_action %}
    <p style="font-family: 'Noto Sans Arabic', sans-serif;"> <span style="color: green">اقدامات بعدی :</span> <br>
        {{ next_action }}
    </p>
    {% endif %}
    <p style="font-family: 'Noto Sans Arabic', sans-serif;text-align: center">
        <span style="color: crimson ;font-size: 20px;text-align: center;display: block;width: 100%;margin: 0 auto">توجه :</span>
    </p>
    <u><p style="font-family: 'Noto Sans Arabic', sans-serif;font-size: 15px;text-align: center;margin-top: 15px">لطفا دریافت این ایمیل را با پاسخ گویی به همین ایمیل تایید کرده و پیشرفت کار را گزارش کنید</p></u>
    <u><p style="font-family: 'Noto Sans Arabic', sans-serif;font-size: 15px;text-align: center;margin-top: 15px">فلوچارت مراحل نیز در زیر قابل مشاهده است</p></u>

    <p style="text-align:center;">
        <img src="cid:{{ rand_string }}" alt="" style="border-radius: 35px;height: 100%; width:80%">
    </p>
    <p style="text-align:center;">
        <img src="cid:{{ rand_string }}_severity" alt="" style="border-radius: 35px;height: 100%; width:80%">
    </p>
    <p id="flowchart_id" style="display: none">{{ flowchart_id }}</p>



</section>
</body>
</html>

users/templates/users/email_response.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Email Response</title>
    <link rel="icon" href="{% static 'img/favicon.png' %}">
    <link rel="stylesheet" href="{% static 'node_modules/bootstrap/dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'font awesome/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
    <style>


        .new-message-box {
            margin: 250px auto !important;
            padding-left: 20px;
            margin-bottom: 25px !important;
        }

        .new-message-box p {
            font-size: 1.15em;
            font-weight: 600;
        }

        .row {
            justify-content: center;
        }

        .info-tab {
            width: 40px;
            height: 40px;
            display: inline-block;
            position: relative;
            top: 8px;
        }

        .info-tab {
            float: left;
            margin-left: -23px;
        }

        .info-tab i::before {
            width: 24px;
            height: 24px;
            box-shadow: inset 12px 0 13px rgba(0, 0, 0, 0.5);
        }

        .info-tab i::after {
            width: 0;
            height: 0;
            border: 12px solid transparent;
            border-bottom-color: #fff;
            border-left-color: #fff;
            bottom: -18px;
        }

        .info-tab i::before, .info-tab i::after {
            content: "";
            display: inline-block;
            position: absolute;
            left: 0;
            bottom: -17px;
            transform: rotateX(60deg);
        }

        .note-box, .warning-box, .tip-box-success, .tip-box-danger, .tip-box-warning, .tip-box-info, .tip-box-alert {
            padding: 12px 8px 3px 26px;
        }


        /***Success****/

        .new-message-box-success {
            background: #eeeeee;
            padding: 3px;
            margin: 10px 0;
        }

        .tip-icon-success {
            background: #376900;
        }

        .tip-box-success {
            color: #33691E;
            background: #b9e5b5;
        }

        .tip-icon-success::before {
            font-size: 25px;
            content: "\f00c";
            top: 3px;
            left: 8px;
            font-family: FontAwesome;
            position: absolute;
            color: white;
        }

        .tip-icon-success i::before {
            background: #8BC34A;
        }


        /*******Danger*******/
        .new-message-box-danger {
            background: #eeeeee;
            padding: 3px;
            margin: 10px 0;
        }

        .tip-icon-danger {
            background: #f44336;
        / / 500
        }

        .tip-box-danger {
            color: #cb0707;
            background: #FFCCBC;
        }

        .tip-icon-danger::before {
            font-size: 25px;
            content: "\f00d";
            top: 3px;
            left: 8px;
            font-family: FontAwesome;
            position: absolute;
            color: white;
        }

        .tip-icon-danger i::before {
            background: #f44336;
        / / 500
        }

        /*******warning*******/
        .new-message-box-warning {
            background: red;
            padding: 3px;
            margin: 10px 0;
        }

        .tip-icon-warning {
            background: #FFEB3B;
        / / 500
        }

        .tip-box-warning {
            color: #212121;
        / / 900 background: #FFF9C4;
        / / 100
        }

        .tip-icon-warning::before {
            font-size: 25px;
            content: "\f071";
            top: 8px;
            left: 11px;
            position: absolute;
            color: #212121;
        }

        .tip-icon-warning i::before {
            background: #FFEB3B;
        / / 500
        }


        /*************************/

        body {
            background-color: #ffffff;
        }
    </style>
</head>
<body>

<div class="container-fluid text-center">
    {% if state  %}
        <div class="row">
            <div class="col-xs-12 col-sm-6 col-sm-offset-3">
                <div class="new-message-box">
                    <div class="new-message-box-success">
                        <div class="info-tab tip-icon-success" title="success"><i></i></div>
                        <div class="tip-box-success">
                            <p>Your response submitted successfully</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% else %}
        <div class="row">
            <div class="col-xs-12 col-sm-6 col-sm-offset-3 ">
                <div class="new-message-box">
                    <div class="new-message-box-danger">
                        <div class="info-tab tip-icon-danger" title="error"><i></i></div>
                        <div class="tip-box-danger">
                            <!--<p><strong>Tip:</strong> If you want to enable the fading transition effect while closing the alert boxes, apply the classes <code>.fade</code> and <code>.in</code> to them along with the contextual class.</p>-->
                            <p>Invalid Link!</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}


</div>


<script src="{% static 'node_modules/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>